DROP DATABASE IF EXISTS CORONAVIRUSAPP;
CREATE DATABASE CORONAVIRUSAPP;
USE CORONAVIRUSAPP;

CREATE TABLE USUARIO(
	nombre VARCHAR(30) NOT NULL,
    PRIMARY KEY(nombre)
);
CREATE TABLE PUNTAJE(
	id INT NOT NULL auto_increment,
    PRIMARY KEY(id),
    valor INT NOT NULL,
    nombreFK VARCHAR(30) NOT NULL,
    FOREIGN KEY (nombreFK) REFERENCES USUARIO(nombre)
);
SELECT * FROM USUARIO;
SELECT * FROM PUNTAJE;

CREATE VIEW PUNTAJES_MAXIMOS as
SELECT u.NOMBRE, MAX(p.valor) as PUNTAJEMAXIMO 
FROM USUARIO as u 
INNER JOIN PUNTAJE as p 
ON u.nombre = p.nombreFK GROUP BY NOMBRE;

SELECT * FROM PUNTAJES_MAXIMOS ORDER BY PUNTAJEMAXIMO DESC;
INSERT INTO USUARIO(nombre) VALUES ("juan");
INSERT INTO PUNTAJE(valor,nombreFK) VALUES (2, 'JUAN');